version: '3.8'

services:
  cowrie-ubuntu:
    build: ./app
    container_name: honeypot-ubuntu
    ports:
      - "2222:2222"
    volumes:
      - ./logs/ubuntu:/cowrie/cowrie-git/var/log/cowrie
      - ./app/configs/ubuntu.cfg:/cowrie/cowrie-git/etc/cowrie.cfg:ro
    restart: unless-stopped

  cowrie-cisco:
    build: ./app
    container_name: honeypot-cisco
    ports:
      - "2223:2222"
    volumes:
      - ./logs/cisco:/cowrie/cowrie-git/var/log/cowrie
      - ./app/configs/cisco.cfg:/cowrie/cowrie-git/etc/cowrie.cfg:ro
    restart: unless-stopped

  cowrie-windows:
    build: ./app
    container_name: honeypot-windows
    ports:
      - "2224:2222"
    volumes:
      - ./logs/windows:/cowrie/cowrie-git/var/log/cowrie
      - ./app/configs/windows.cfg:/cowrie/cowrie-git/etc/cowrie.cfg:ro
    restart: unless-stopped