apiVersion: v1
kind: Service
metadata:
  name: honeypot-web-server
  labels:
    app: honeypot
    type: web-server
spec:
  type: NodePort
  selector:
    app: honeypot
    type: web-server
  ports:
  - name: ssh
    port: 22
    targetPort: 2222
    nodePort: 30022
---
apiVersion: v1
kind: Service
metadata:
  name: honeypot-edge-router
  labels:
    app: honeypot
    type: edge-router
spec:
  type: NodePort
  selector:
    app: honeypot
    type: edge-router
  ports:
  - name: ssh
    port: 22
    targetPort: 2222
    nodePort: 30023
  - name: telnet
    port: 23
    targetPort: 232
    nodePort: 30024
---
apiVersion: v1
kind: Service
metadata:
  name: honeypot-domain-controller
  labels:
    app: honeypot
    type: domain-controller
spec:
  type: NodePort
  selector:
    app: honeypot
    type: domain-controller
  ports:
  - name: ssh
    port: 22
    targetPort: 2222
    nodePort: 30025
