apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowrie-deployment
  labels:
    app: honeypot
    type: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: honeypot
      type: web-server
  template:
    metadata:
      labels:
        app: honeypot
        type: web-server
    spec:
      containers:
        - name: cowrie
          image: cowrie/cowrie:latest
          ports:
            - containerPort: 2222