apiVersion: v1
kind: Pod
metadata:
  name: cowrie-pod
  labels:
    app: honeypot
    type: web-server
spec:
  containers:
    - name: cowrie
      image: cowrie/cowrie:latest
      ports:
        - containerPort: 2222
